language: go

go:
  - "1.13.x"

install: true

before_install:
  - export TZ=America/Chicago
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.19.1
  - golangci-lint --version
  - go get github.com/mattn/goveralls
  - export PATH=$(pwd)/bin:$PATH

script:
  - export GO111MODULE=on
  - go get ./...
  - go test -v -covermode=count -coverprofile=profile.cov ./... || travis_terminate 1;
  - golangci-lint run  || travis_terminate 1;
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
